### ISSUE TITLE
 UserWarning: nn.Upsample is deprecated.

### ISSUE THREAD

**Issue by Lornatang** [eriklindernoren/PyTorch-GAN#46]
*Hi~*

**I found an error while using InfoGAN. The error is as follows. Hope to repair.**

```text
/usr/local/lib/python3.7/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
/usr/local/lib/python3.7/site-packages/torch/nn/modules/container.py:92: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
```
**Thank you for writing the code, gave me a lot of inspiration!**

**Comment by alsombra** [comment]
This actually is not an error, it's just a warning. You don't need to worry about it.

If you want, you can just change the `torch.nn.Upsample()` layer  for  the function `torch.nn.functional.interpolate()` and choose the same interpolation method to have same behavior, e.g., change `torch.nn.Upsample(mode='nearest', scale_factor=2)(x_in)` to `torch.nn.functional.interpolate(x_in, mode='nearest', scale_factor=2)`.

 The problem is that `nn.function.interpolate` does not have bicubic interpolation implementation. In this case I transform the tensor back to numpy array and use any existing implemantion for it (like the PIL.Image.resize), then transform it back to Tensor (not sure if it is intelligent, but does the trick). There is a nice dicussion about this change [here](https://discuss.pytorch.org/t/which-function-is-better-for-upsampling-upsampling-or-interpolate/21811/7).

**Comment by eriklindernoren** [comment]
Just like @alsombra said it's just a warning, so you can run the implementations without problems despite the message you got. That said, I will probably write a wrapper for `torch.nn.functional.interpolate` soon which will replace the `nn.Upsample` layers.

**Comment by eriklindernoren** [comment]
Haven't had time to add this yet. Have to decide if I want to add this custom layer to each implementation or if I should add a common python file with custom layers. If you want to get rid of this message you can use this `Upsample` module. 

```python
class Upsample(nn.Module):
    """ nn.Upsample is deprecated """

    def __init__(self, scale_factor, mode="nearest"):
        super(Upsample, self).__init__()
        self.scale_factor = scale_factor
        self.mode = mode

    def forward(self, x):
        x = F.interpolate(x, scale_factor=self.scale_factor, mode=self.mode)
        return x
```

**Comment by Lornatang** [comment]
Thank you so much  l got it.
